services:
  app:
    build:
      context: .
      target: production
    image: cashvan-api:prod
    restart: always
    environment:
      - NODE_ENV=production
    ports: !reset []
    expose:
      - "3000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  db:
    ports: !reset []
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
